name: 'GitHub Workflow Security Scanner'
description: 'A GitHub Action that performs static analysis on your workflows'
inputs:
  GH_TOKEN:
    description: 'Github token'
    required: true
  SHOULD_BREAK:
    description: 'Boolean to determine if CI should break when a vulnerability is found'
    required: false
    default: false
  TYPE:
    description: 'Type of resource to be analysed. Three acceptable values: repo, org, user'
    default: 'repo'
  TARGET:
    description: 'Org or user name, or repository with format "owner/reponame"'
  BRANCH:
    description: 'Branch to run the scan on.'
    default: 'HEAD'
  
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/checkout@v3
      with:
        repository: 'magmanu/github-workflow-scanner'
        ref: 'feat/supply-chain'
    
    - name: Install Dependencies
      run: |
        pwd
        pip install -r requirements.txt
        pip install python-dotenv
      shell: bash

    - name: Run scan
      run: | 
          export COUNT=$(python main.py)
          echo "VULN_COUNT=$COUNT" >> $GITHUB_ENV
          filename='result.md'
          while read line; do echo "$line" >> $GITHUB_STEP_SUMMARY; done < $filename
      env:
        TARGET_TYPE: "repo"
        TARGET_INPUT: ${{ env.TARGET }}
        TOKEN: ${{ inputs.GH_TOKEN }}
        TARGET_BRANCH: ${{ inputs.BRANCH }}
      shell: bash

    - name: Terminate if vuln > 0
      env: 
        SHOULD_BREAK: ${{ fromJSON(inputs.SHOULD_BREAK) }}
        VULN_COUNT: ${{ env.VULN_COUNT }}
      run: |
        if ([ $VULN_COUNT -gt 0 ] && [ $SHOULD_BREAK = true ])
        then
          exit 1
        else
          exit 0
        fi
      shell: bash

